import { AvailableSpace } from './types';

export const dummyAvailableSpaces: AvailableSpace[] = [
  {
    id: '1',
    name: 'Starbucks Downtown',
    description: 'Spacious coffee shop with WiFi and seating area',
    availableTimes: [
      { day: 'Monday', startTime: '09:00', endTime: '18:00' },
      { day: 'Tuesday', startTime: '09:00', endTime: '18:00' },
      { day: 'Wednesday', startTime: '09:00', endTime: '18:00' },
      { day: 'Thursday', startTime: '09:00', endTime: '18:00' },
      { day: 'Friday', startTime: '09:00', endTime: '18:00' },
      { day: 'Saturday', startTime: '10:00', endTime: '17:00' },
      { day: 'Sunday', startTime: '10:00', endTime: '17:00' },
    ],
    maxOccupancy: 15,
    costPerHour: 5,
    address: '123 Main St, Downtown',
  },
  {
    id: '2',
    name: 'Din Tai Fung',
    description: 'Modern restaurant with private dining areas and catering available',
    availableTimes: [
      { day: 'Monday', startTime: '11:00', endTime: '22:00' },
      { day: 'Tuesday', startTime: '11:00', endTime: '22:00' },
      { day: 'Wednesday', startTime: '11:00', endTime: '22:00' },
      { day: 'Thursday', startTime: '11:00', endTime: '22:00' },
      { day: 'Friday', startTime: '11:00', endTime: '23:00' },
      { day: 'Saturday', startTime: '11:00', endTime: '23:00' },
      { day: 'Sunday', startTime: '11:00', endTime: '21:00' },
    ],
    maxOccupancy: 30,
    costPerHour: 25,
    address: '456 Oak Ave, Downtown',
  },
  {
    id: '3',
    name: 'The Creative Studio',
    description: 'Flexible workspace with natural lighting and modern amenities',
    availableTimes: [
      { day: 'Monday', startTime: '08:00', endTime: '20:00' },
      { day: 'Tuesday', startTime: '08:00', endTime: '20:00' },
      { day: 'Wednesday', startTime: '08:00', endTime: '20:00' },
      { day: 'Thursday', startTime: '08:00', endTime: '20:00' },
      { day: 'Friday', startTime: '08:00', endTime: '20:00' },
      { day: 'Saturday', startTime: '09:00', endTime: '18:00' },
    ],
    maxOccupancy: 20,
    costPerHour: 15,
    address: '789 Elm Street, Arts District',
  },
  {
    id: '4',
    name: 'Lakeside Event Hall',
    description: 'Spacious event venue with waterfront views and full kitchen facilities',
    availableTimes: [
      { day: 'Friday', startTime: '18:00', endTime: '23:00' },
      { day: 'Saturday', startTime: '10:00', endTime: '23:00' },
      { day: 'Sunday', startTime: '10:00', endTime: '21:00' },
    ],
    maxOccupancy: 100,
    costPerHour: 50,
    address: '1000 Water View Dr, Lakeside',
  },
  {
    id: '5',
    name: 'Green Leaf Cafe',
    description: 'Cozy cafe with outdoor garden seating and organic menu',
    availableTimes: [
      { day: 'Monday', startTime: '07:00', endTime: '19:00' },
      { day: 'Tuesday', startTime: '07:00', endTime: '19:00' },
      { day: 'Wednesday', startTime: '07:00', endTime: '19:00' },
      { day: 'Thursday', startTime: '07:00', endTime: '19:00' },
      { day: 'Friday', startTime: '07:00', endTime: '20:00' },
      { day: 'Saturday', startTime: '08:00', endTime: '20:00' },
      { day: 'Sunday', startTime: '09:00', endTime: '18:00' },
    ],
    maxOccupancy: 12,
    costPerHour: 8,
    address: '321 Park Lane, Garden District',
  },
  {
    id: '6',
    name: 'Tech Hub Coworking',
    description: 'State-of-the-art coworking space with high-speed internet and meeting rooms',
    availableTimes: [
      { day: 'Monday', startTime: '06:00', endTime: '22:00' },
      { day: 'Tuesday', startTime: '06:00', endTime: '22:00' },
      { day: 'Wednesday', startTime: '06:00', endTime: '22:00' },
      { day: 'Thursday', startTime: '06:00', endTime: '22:00' },
      { day: 'Friday', startTime: '06:00', endTime: '22:00' },
      { day: 'Saturday', startTime: '09:00', endTime: '18:00' },
    ],
    maxOccupancy: 25,
    costPerHour: 12,
    address: '555 Innovation Blvd, Tech Park',
  },
];
